#!/bin/bash

CONFIG_FILE=~/.stash3

if [ ! -e $CONFIG_FILE ]; then
    echo "Looks like you haven't configured stash3 yet :)"
    echo
    read -p "Where's the bucket? " bucket
    echo $bucket > $CONFIG_FILE

    if [ -n "$AWS_PROFILE" ]; then
        echo $AWS_PROFILE >> $CONFIG_FILE
    fi
fi

bucket=$(head -n 1 $CONFIG_FILE)

if [ $(wc -l <$CONFIG_FILE) -eq 2 ]; then
    export AWS_PROFILE=$(tail -n 1 $CONFIG_FILE)
fi

case ${#@} in
    0)
        # List everything
        aws s3api list-objects --bucket $bucket --query Contents[].Key --output text | sort -h
        ;;
    2)
        file=$1
        name=$2

        if [[ $file =~ ^https?:// ]]; then
            f=$(mktemp)
            aws s3 cp $f s3://$bucket/$name \
                --acl public-read \
                --website-redirect $file \
                > /dev/null
            rm $f
        elif [ -f $file ]; then
            aws s3 cp $file s3://$bucket/$name \
                --acl public-read \
                --no-guess-mime-type \
                --content-type $(file -b --mime-type $file) \
                --content-encoding $(file -b --mime-encoding $file) \
                > /dev/null
        else
            echo "Couldn't figure out what '$file' is" >&2
            exit 1
        fi

        echo http://$bucket/$name

        ;;
    *)
        echo "Usage: stash3 (<file name | URL> <clip name>)"
        echo "  If you supply no arguments, list the contents of your bucket"
        echo "  If you supply two arguments, store the file in the clip or link to the url"
        ;;
esac
